# 生产环境
server:
  port: 8090

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mariadb://120.79.138.62:3307/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: foodie
    password: 123456
  redis:
    database: 1
    host: 120.79.138.62
    port: 6379
    password: abc123